spring:
  thymeleaf:
    mode: HTML

schedule:
  satisfy:
    #每分钟执行一次
    drinkWater: 1 * * * * ?
    #每天6点执行一次
    whether: 0 0 6 ? * *

thread-pool:
  corePoolSize: 10
  maximumPoolSize: 10

# sl4j 配置
logging:
  level:
    sunhongbin:
      # 开 debug 模式
      service: debug
      # 日志输出格式：%d表示日期时间，%thread表示线程名，%-5level：级别从左显示5个字符宽度 %logger{50} 表示logger名字最长50个字符，否则按照句点分割 %msg：日志消息 %n 换行符
  pattern: console:%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n